# Generated by Django 3.2 on 2021-04-23 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Koszyk',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Plyta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tytul', models.CharField(max_length=200)),
                ('dostepna_ilosc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Produkt_koszyka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.IntegerField()),
                ('koszyk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plyty.koszyk')),
                ('plyta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plyty.plyta')),
            ],
            options={
                'unique_together': {('plyta', 'koszyk')},
            },
        ),
    ]
