# Generated by Django 3.2 on 2021-06-16 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plyty', '0002_koszyk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pluty_koszyk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.IntegerField()),
                ('koszyk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plyty.koszyk')),
                ('plyta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plyty.plyta')),
            ],
            options={
                'unique_together': {('plyta', 'koszyk')},
            },
        ),
    ]
