# Generated by Django 3.2 on 2021-06-16 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plyty', '0003_pluty_koszyk'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pluty_koszyk',
            new_name='Plyty_koszyk',
        ),
    ]
